prompt: BehaviorPromptManager
prompt_kwargs:
   # Task prompt
   task_prompt:
      # Task     
      task: packing_4
      instruction: "Put all the objects on the shelf."
      objects: 
         - "object_1"
         - "object_2"
         - "object_3"
         - "object_4"
         - "object_5"
         - "ground"
         - "shelf"
      predicates: 
         - "On(object_1, ground)"
         - "On(object_2, ground)"
         - "On(object_3, ground)"
         - "On(object_4, ground)"
         - "On(object_5, ground)"
         
      # Behaviors
      goals: Null
      plans: Null
      hypotheses: Null
      geometric: Null

      # OpenAI
      role: user
      name: Null
      name_query: Null
      name_response: Null
      
   # System prompts
   system_prompts:
      - LLM/configs/prompts/system/goal_prediction_v1.yaml
      - LLM/configs/prompts/system/task_planning_goal_condition_v1.yaml

   # Example prompts
   example_prompts:
      - LLM/configs/prompts/examples/example_1.yaml
      - LLM/configs/prompts/examples/example_2.yaml
      - LLM/configs/prompts/examples/example_3.yaml

   # Event prompts
   event_prompts: Null