prompt: BehaviorPromptManager
prompt_kwargs:
   # Task prompt
   task_prompt:
      # Task
      task: retrieval_2_v2
      instruction: "Retrieve object_1."
      objects: 
         - "object_1"
         - "object_2"
         - "object_3"
         - "object_4"
         - "shelf"
         - "ground"
      predicates: 
         - "On(object_1, shelf)"
         - "On(object_2, shelf)"
         - "On(object_3, shelf)"
         - "On(object_4, shelf)"
         - "Blocking(object_3, object_4)"
         - "Blocking(object_3, object_1)"
         - "Blocking(object_2, object_1)"
         - "Blocking(object_4, object_1)"

      # Behaviors
      goals: [["On(object_1, ground)"]]
      plans: Null
      hypotheses: Null
      geometric: Null

      # OpenAI
      role: user
      name: Null
      name_query: Null
      name_response: Null
      
   # System prompts
   system_prompts:
      - LLM/configs/prompts/system/goal_prediction_v2.yaml
      - LLM/configs/prompts/system/task_planning_goal_condition_v2.yaml

   # Example prompts
   example_prompts:
      - LLM/configs/prompts/examples/example_4.yaml
      - LLM/configs/prompts/examples/example_5.yaml

   # Event prompts
   event_prompts: Null